services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app 
      - /app/node_modules 
    command: npm run dev 
    restart: unless-stopped