version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: parker-database
      POSTGRES_USER: parker-username
      POSTGRES_PASSWORD: parker-password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/app
    ports:
      - "5050:5000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=parker-database
      - DATABASE_USER=parker-username
      - DATABASE_PASSWORD=parker-password
      - DATABASE_HOST=db

  backend-web:
      build: .
      ports: 
        - "5051:5000"
      env_file:
        - .env
      depends_on:
        - db