# Generated by Django 5.2.1 on 2025-05-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cookTime', models.TextField()),
                ('ingredients', models.JSONField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
